trigger:
  branches:
    include:
      - 'develop'
      - 'qa'
      - 'master'

pr:
  branches:
    include:
      - 'develop'
      - 'qa'
      - 'master'

variables:
  serviceName: shell-application-poc

pool:
  name: Azure Pipelines
  demands:
    - java

stages:
  - stage: DeployToKubernetesDev
    displayName: Deploy to Kubernetes - Dev
    dependsOn: []
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - deployment: DeployToKubernetesDev
        displayName: Deploy to Kubernetes - Dev
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: current
                    artifactName: HelmChart
                - task: CopyFiles@2
                  displayName: Copy HelmChart Folder to Default Working Directory
                  inputs:
                    SourceFolder: $(Pipeline.Workspace)/HelmChart
                    TargetFolder: $(System.DefaultWorkingDirectory)
                    Contents: '**'
                - task: HelmDeploy@0
                  displayName: Helm Upgrade - Dev
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: Tatatele-Caxsol
                    azureResourceGroup: cax_peopleanalytics_rg
                    kubernetesCluster: caxallenvakspa01
                    namespace: people-analytics-dev
                    command: upgrade
                    chartType: FilePath
                    chartPath: $(System.DefaultWorkingDirectory)/shell-app-chart
                    releaseName: pa-shell-app-dev-poc
                    overrideValues: image.tag=4761
                    valueFile: $(System.DefaultWorkingDirectory)/values-dev.yaml

  - stage: DeployToKubernetesQA
    displayName: Deploy to Kubernetes - QA
    dependsOn: []
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/qa'))
    jobs:
      - deployment: DeployToKubernetesQA
        displayName: Deploy to Kubernetes - QA
        environment: QA
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: current
                    artifactName: HelmChart
                - task: CopyFiles@2
                  displayName: Copy HelmChart Folder to Default Working Directory
                  inputs:
                    SourceFolder: $(Pipeline.Workspace)/HelmChart
                    TargetFolder: $(System.DefaultWorkingDirectory)
                    Contents: '**'
                - task: HelmDeploy@0
                  displayName: Helm Upgrade - QA
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: Tatatele-Caxsol
                    azureResourceGroup: cax_peopleanalytics_rg
                    kubernetesCluster: caxallenvakspa01
                    namespace: people-analytics-qa
                    command: upgrade
                    chartType: FilePath
                    chartPath: $(System.DefaultWorkingDirectory)/shell-app-chart
                    releaseName: pa-shell-app-qa
                    overrideValues: image.tag=$(Build.BuildId)
                    valueFile: $(System.DefaultWorkingDirectory)/values-qa.yaml

  - stage: DeployToKubernetesProd
    displayName: Deploy to Kubernetes - Prod
    dependsOn: []
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: DeployToKubernetesProd
        displayName: Deploy to Kubernetes - Prod
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: current
                    artifactName: HelmChart
                - task: CopyFiles@2
                  displayName: Copy HelmChart Folder to Default Working Directory
                  inputs:
                    SourceFolder: $(Pipeline.Workspace)/HelmChart
                    TargetFolder: $(System.DefaultWorkingDirectory)
                    Contents: '**'
                - task: HelmDeploy@0
                  displayName: Helm Upgrade - Prod
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscription: Tatatele-Caxsol
                    azureResourceGroup: cax_peopleanalytics_rg
                    kubernetesCluster: caxallenvakspa01
                    namespace: people-analytics-prod
                    command: upgrade
                    chartType: FilePath
                    chartPath: $(System.DefaultWorkingDirectory)/shell-app-chart
                    releaseName: pa-shell-app-prod
                    overrideValues: image.tag=$(Build.BuildId)
                    valueFile: $(System.DefaultWorkingDirectory)/values-prod.yaml
