export const environment = {
  name: 'development',
  port: 8000,
  // base_url: 'http://4.224.92.30:8080/',
  base_url: process.env?.BASE_URL,
  production: false,
  // authMfeUrl: 'http://4.224.104.252:8081/remoteEntry.js',
  authMfeUrl: `${process.env?.AUTHAPP_URL}remoteEntry.js`,
  authRemoteName: 'authapp',
  authExpModule: './authApp',
  reactLandingUrl: 'http://4.188.109.166:8086/remoteEntry.js',
  reactRemoteName: 'landing',
  reactExpModule: './landing',
  // styleguideUrl: 'http://4.187.144.99:8082/remoteEntry.js',
  styleguideUrl: `${process.env?.STYLEGUIDE_URL}remoteEntry.js`,
  styleguideRemoteName: 'styleguide',
  styleguideExpoModule: './styleguide',
  assistantParcelUrl: 'http://20.235.192.190:8087/remoteEntry.js',
  assistantParcelRemoteName: 'assistantParcel',
  assistantParcelExpoModule: './assistantParcel',
  userProfileUrl: `${process.env?.PROFILE_URL}remoteEntry.js`,
  userProfileRemoteName: 'user_profile',
  userProfileExpoModule: './user_profile',
};
