export const environment = {
  name: 'qa',
  port: 8080,
  base_url: 'https://localhost:8080',
  production: false,
  authMfeUrl: 'http://localhost:8081/remoteEntry.js',
  authRemoteName: 'authApp',
  authExpModule: './authapp',
  reactLandingUrl: 'http://localhost:8086/remoteEntry.js',
  reactRemoteName: 'landing',
  reactExpModule: './landing',
  userProfileUrl: 'http://20.235.192.190:8087/remoteEntry.js',
  userProfileRemoteName: 'assistantParcel',
  userProfileExpoModule: './assistantParcel',
};
